"""empty message

Revision ID: 38262a0a6d5d
Revises: 
Create Date: 2022-03-22 19:12:41.415258

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38262a0a6d5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raceresult",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Integer(), nullable=True),
        sa.Column("quali", sa.String(length=100), nullable=True),
        sa.Column("sprint", sa.String(length=100), nullable=True),
        sa.Column("first", sa.String(length=100), nullable=True),
        sa.Column("second", sa.String(length=100), nullable=True),
        sa.Column("third", sa.String(length=100), nullable=True),
        sa.Column("fastest_lap", sa.String(length=100), nullable=True),
        sa.Column("safety_car", sa.String(length=100), nullable=True),
        sa.Column("bonus", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["race.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id"),
    )
    op.add_column("raceguess", sa.Column("bonus_ok", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raceguess", "bonus_ok")
    op.drop_table("raceresult")
    # ### end Alembic commands ###
