"""Added Standings table

Revision ID: bc1752622663
Revises: 38262a0a6d5d
Create Date: 2022-11-18 13:47:17.710432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc1752622663"
down_revision = "38262a0a6d5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "standings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=True),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("points", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("standings")
    # ### end Alembic commands ###
