name: Tox tests

on: [push, pull_request]

jobs:
  py313:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py313